export enum HospitalDepartment {
    EMERGENCY = "Emergency Department",
    CARDIOLOGY = "Cardiology",
    NEUROLOGY = "Neurology",
    ORTHOPEDICS = "Orthopedics",
    ONCOLOGY = "Oncology",
    PEDIATRICS = "Pediatrics",
    GYNECOLOGY = "Gynecology",
    DERMATOLOGY = "Dermatology",
    RADIOLOGY = "Radiology",
    PHARMACY = "Pharmacy",
    INTERNAL_MEDICINE = "Internal Medicine",
    SURGERY = "Surgery",
    ANESTHESIOLOGY = "Anesthesiology",
    PSYCHIATRY = "Psychiatry",
    PATHOLOGY = "Pathology",
    OPHTHALMOLOGY = "Ophthalmology",
    GASTROENTEROLOGY = "Gastroenterology",
    UROLOGY = "Urology",
    NEPHROLOGY = "Nephrology",
    ALLERGY = "Allergy and Immunology",
    REHABILITATION = "Rehabilitation",
    HEMATOLOGY = "Hematology",
    RHEUMATOLOGY = "Rheumatology",
    PULMONOLOGY = "Pulmonology"
}
